name: chat_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^7.9.2
  dio: ^5.8.0+1
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_profile_picture: ^2.0.0
  flutter_svg: ^2.2.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.1
  get_it: ^8.2.0
  google_sign_in: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  toastification: ^3.0.3

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/imgs/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto_Condensed-ExtraBold.ttf
          weight: 800

    - family: Trebuc
      fonts:
        - asset: assets/fonts/trebuc/trebuc.ttf
          weight: 400
